apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
    - ssh:
        address: 34.51.130.179
        user: vuchuc
        port: 22
        keyPath: ./instance_key
      role: controller
    - ssh:
        address: 34.51.188.165
        user: vuchuc
        port: 22
        keyPath: ./instance_key
      role: worker
      # - ssh:
      #     address: 34.51.129.110
      #     user: vuchuc
      #     port: 22
      #     keyPath: ./instance_key
      #   role: worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
